# Funding Configuration

# These usernames will be linked to GitHub Sponsors
github:
  - animeshahilya

# Add other platforms if applicable
# open_collective: []
# patreon: []
# tidelift: []
# custom: []