"""Indic inherent-vowel slots (gu, pa, ne, hi, mr, bn): what eSpeak does now and what
WikiPron wants.

usage: python indic_slots.py LANG WIKIPRON_TSV

Needs LANG_nodel.tsv and LANG_norm.tsv (generated by dump_nodel.py).
Each inherent vowel is mapped to its position in the no-deletion output; the reference
alignment says whether it should be kept, and the normal output says
whether eSpeak keeps it today. Writes LANG_slots.tsv: word, index, want, now (DROP/KEEP).
"""
import collections, sys
import score as S

SCRIPTS = {
    'deva': {
        'cons': set(chr(c) for c in range(0x915, 0x93A)) | set(chr(c) for c in range(0x958, 0x960)),
        'signs': set(chr(c) for c in range(0x93E, 0x94D)) | {'ॢ', 'ॣ'},
        'indep': set(chr(c) for c in range(0x904, 0x915)) | {'ॠ', 'ॡ'},
        'virama': '्',
        'nukta': '़',
        'inh_char': 'अ',
        'nasals': 'ंँ',
    },
    'gujr': {
        'cons': set(chr(c) for c in range(0x0A95, 0x0ABA)),
        'signs': set(chr(c) for c in range(0x0ABE, 0x0ACD)) | {'ૢ', 'ૣ', 'ૅ', 'ૉ'},
        'indep': set(chr(c) for c in range(0x0A85, 0x0A95)) | {'ૠ', 'ૡ', 'ઍ', 'ઑ'},
        'virama': '્',
        'nukta': '઼',
        'inh_char': 'અ',
        'nasals': 'ંઁ',
    },
    'guru': {
        'cons': set(chr(c) for c in range(0x0A15, 0x0A3A)) | set(chr(c) for c in range(0x0A59, 0x0A5F)) | {'ਲ਼', 'ਸ਼'},
        'signs': set(chr(c) for c in range(0x0A3E, 0x0A4D)),
        'indep': set(chr(c) for c in range(0x0A05, 0x0A15)),
        'virama': '੍',
        'nukta': '਼',
        'inh_char': 'ਅ',
        'nasals': 'ੰਂ',
    },
    'beng': {
        'cons': set(chr(c) for c in range(0x0995, 0x09BA)) | set('ড়ঢ়য়'),
        'signs': set('ািীুূৃৄেৈোৌ'),
        'indep': set('অআইঈউঊঋএঐওঔ'),
        'virama': '্',
        'nukta': '়',
        'inh_char': 'অ',
        'nasals': 'ংঁঃ',
    },
}

LANG_SCRIPT = {
    'hi': 'deva',
    'mr': 'deva',
    'ne': 'deva',
    'gu': 'gujr',
    'pa': 'guru',
    'bn': 'beng',
}

VOWELS = set('aeiouəʌɔ')


def sources(word, s):
    out = []
    for i, ch in enumerate(word):
        nxt = word[i + 1] if i + 1 < len(word) else ''
        if nxt == s['nukta']:
            nxt = word[i + 2] if i + 2 < len(word) else ''
        if ch in s['indep']:
            out.append((i, 'inh' if ch == s['inh_char'] else 'exp'))
        elif ch in s['signs']:
            out.append((i, 'exp'))
        elif ch in s['cons'] and nxt not in s['signs'] and nxt != s['virama']:
            out.append((i, 'inh'))
    return out


def load(path):
    d = {}
    for line in open(path, encoding='utf-8'):
        w, _, g = line.rstrip('\n').partition('\t')
        d[w] = g
    return d


def main():
    if len(sys.argv) < 3:
        print("usage: python indic_slots.py LANG WIKIPRON_TSV")
        sys.exit(1)
    lang, tsv = sys.argv[1], sys.argv[2]
    script_name = LANG_SCRIPT.get(lang, 'deva')
    s = SCRIPTS[script_name]

    ref = {}
    for line in open(tsv, encoding='utf-8'):
        w, _, p = line.rstrip('\n').partition('\t')
        if ' ' not in w and w not in ref:
            ref[w] = p

    nodel, norm = load(f'{lang}_nodel.tsv'), load(f'{lang}_norm.tsv')
    rows, used, skipped = [], 0, 0

    for w in ref:
        if w not in nodel or w not in norm:
            continue
        gp = S.phones(nodel[w])
        src = sources(w, s)
        gv = [k for k, p in enumerate(gp) if p[:1] in VOWELS]
        if len(gv) == len(src) - 1 and src and src[-1][1] == 'inh':
            src = src[:-1]                     # final inherent vowel, never spoken
        if len(gv) != len(src):
            skipped += 1
            continue
        used += 1

        # ᵊ is a brief vowel release; eSpeak says it as @-
        ref_ipa = ref[w].replace('ᵊ', 'ə')
        _, pr = S.align(S.phones(ref_ipa), gp)  # reference vs no-deletion
        _, pn = S.align(gp, S.phones(norm[w]))  # no-deletion vs normal
        want, now = {}, {}
        k = 0
        for a, b in pr:
            if b != '∅':
                want[k] = a != '∅'
                k += 1
        k = 0
        for a, b in pn:
            if a != '∅':
                now[k] = b != '∅'
                k += 1

        for (idx, kind), gpos in zip(src, gv):
            if kind != 'inh' or idx == 0:
                continue
            rows.append((w, idx, 'KEEP' if want.get(gpos, True) else 'DROP',
                         'KEEP' if now.get(gpos, True) else 'DROP'))

    with open(f'{lang}_slots.tsv', 'w', encoding='utf-8') as f:
        for r in rows:
            f.write('%s\t%d\t%s\t%s\n' % r)

    c = collections.Counter((r[2], r[3]) for r in rows)
    print(f'{lang}: words used {used}, skipped {skipped}; slots {len(rows)}')
    print('want/now:', dict(c))


if __name__ == '__main__':
    main()
