"""Urdu word pronunciations taken from the Hindi spelling of each word.

Urdu does not write short vowels, so letter rules cannot know کتاب is
"kitaab". Hindi writes them (किताब), and Google's Dakshina dataset
(CC BY-SA 4.0) has how people type both scripts in Latin letters. Joining
the two through those romanizations maps an Urdu word to its Hindi
spelling; eSpeak's Hindi then gives the vowels, schwa deletion and stress,
and the consonants Hindi spelling loses (ق q, خ x, غ, ز z, ف f, ش) are put
back from the Urdu letters. A match is dropped unless the consonants and
the written long vowels of both spellings line up (آب "water" is not अब
"now").

usage: ur_from_hindi.py DAKSHINA_DIR UR_LIST_IN UR_LIST_OUT [MIN_SHARE]

Needs eSpeak built on the host (espeak-ng/build); the scoring helpers are
in ../schwa/score.py. Words ur_list already has are left out. Safe to re-run: the generated
block at the end of ur_list is replaced.
"""
import collections, glob, os, subprocess, sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'schwa'))
import score as S

HEADER = '// Generated by android/tools/urdu/ur_from_hindi.py'

# --- Devanagari / Urdu letters ---------------------------------------------
VIRAMA, NUKTA = '्', '़'
DCONS = set(chr(c) for c in range(0x915, 0x93A)) | set(chr(c) for c in range(0x958, 0x960))
SIGNS = set(chr(c) for c in range(0x93E, 0x94D))
PRE = dict(zip('क़ख़ग़ज़ड़ढ़फ़', 'कखगजडढफ'))
ASP = {'ख': 'क', 'घ': 'ग', 'छ': 'च', 'झ': 'ज', 'ठ': 'ट', 'ढ': 'ड', 'थ': 'त',
       'ध': 'द', 'फ': 'प', 'भ': 'ब'}
HA2 = 'ھ'
# Urdu consonant -> the Hindi letters it may be written as (nukta dropped).
UR = {
    'ب': 'ब', 'پ': 'प', 'ت': 'त', 'ٹ': 'ट', 'ث': 'स', 'ج': 'ज', 'چ': 'च',
    'ح': 'ह', 'خ': 'ख', 'د': 'द', 'ڈ': 'ड', 'ذ': 'ज', 'ر': 'र', 'ڑ': 'ड',
    'ز': 'ज', 'ژ': 'जझ', 'س': 'स', 'ش': 'शष', 'ص': 'स', 'ض': 'ज', 'ط': 'त',
    'ظ': 'ज', 'غ': 'ग', 'ف': 'फ', 'ق': 'क', 'ک': 'क', 'گ': 'ग', 'ل': 'ल',
    'م': 'म', 'ن': 'नण', 'و': 'व', 'ی': 'य', 'ہ': 'ह', 'ي': 'य', 'ك': 'क',
}
SKIPPABLE = set('اآءئوےیہںن')   # letters that can stand for a vowel or nasal
# Urdu letter -> eSpeak phoneme, for sounds Hindi spelling does not keep.
SUB = {'ق': 'q', 'خ': 'x', 'غ': 'Q', 'ز': 'z', 'ذ': 'z', 'ض': 'z', 'ظ': 'z',
       'ژ': 'Z', 'ف': 'f', 'ش': 'S', 'ڑ': 'r.'}
NUKTA_SOUNDS = ('z', 'f', 'q', 'x', 'Q', 'Z')
HI_LONG = {**dict.fromkeys('ाआ', 'A'), **dict.fromkeys('ोूौओऊऔॉ', 'O'),
           **dict.fromkeys('ीेैईएऐ', 'I')}
UR_LONG = {**dict.fromkeys('اآ', 'A'), 'و': 'O', 'ی': 'I', 'ے': 'I', 'ي': 'I'}


# --- Urdu -> Hindi through romanizations ------------------------------------
def lexicon(dak, lang):
    d = collections.defaultdict(collections.Counter)
    for f in glob.glob(f'{dak}/{lang}/lexicons/*.tsv'):
        for line in open(f, encoding='utf-8'):
            nat, rom, n = line.rstrip('\n').split('\t')
            d[nat][rom.lower()] += int(n)
    return d


def urdu_to_hindi(dak):
    """{urdu: (hindi, share)}: the Hindi word most romanizations point to."""
    ur, hi = lexicon(dak, 'ur'), lexicon(dak, 'hi')
    by_rom = collections.defaultdict(collections.Counter)
    for h, roms in hi.items():
        for r, n in roms.items():
            by_rom[r][h] += n
    out = {}
    for u, roms in ur.items():
        score = collections.Counter()
        for r, n in roms.items():
            cands = by_rom.get(r, {})
            t = sum(cands.values())
            for h, m in cands.items():
                score[h] += n * m / t
        if score:
            h, s = score.most_common(1)[0]
            out[u] = (h, s / sum(roms.values()))
    return out


# --- alignment ----------------------------------------------------------------
def dev_units(h):
    """[(consonant without aspiration, aspirated?, following vowel, letter)]."""
    out = []
    for i, ch in enumerate(h):
        if ch in DCONS:
            j = i + 1
            if j < len(h) and h[j] == NUKTA:
                j += 1
            v = h[j] if j < len(h) and (h[j] in SIGNS or h[j] == VIRAMA) else 'inh'
            base = PRE.get(ch, ch)
            out.append((ASP.get(base, base), base in ASP, v, base))
    return out


def ur_units(u):
    """[(start, end)] of each Urdu letter, a following ھ joined on."""
    out, i = [], 0
    while i < len(u):
        j = i + 1
        if j < len(u) and u[j] == HA2:
            j += 1
        out.append((i, j))
        i = j
    return out


def align(u, units):
    """{Hindi consonant index: Urdu letter index}, or None if they differ."""
    uu = ur_units(u)
    letters = [u[a] for a, _ in uu]
    asp = [b - a > 1 for a, b in uu]
    n, m = len(uu), len(units)
    INF = 10 ** 9
    best = [[INF] * (m + 1) for _ in range(n + 1)]
    back = {}
    best[0][0] = 0
    for i in range(n + 1):
        for j in range(m + 1):
            c = best[i][j]
            if c == INF:
                continue
            if i < n and letters[i] in SKIPPABLE and c + 1 < best[i + 1][j]:
                best[i + 1][j] = c + 1; back[(i + 1, j)] = (i, j, False)
            if i < n and j < m:
                base, hasp, _, letter = units[j]
                cand = UR.get(letters[i], '')
                if ((base in cand and hasp == asp[i]) or (letter in cand and not asp[i])) \
                        and c < best[i + 1][j + 1]:
                    best[i + 1][j + 1] = c; back[(i + 1, j + 1)] = (i, j, True)
    if best[n][m] == INF:
        return None, uu
    pairs, i, j = {}, n, m
    while (i, j) != (0, 0):
        pi, pj, match = back[(i, j)]
        if match:
            pairs[pj] = pi
        i, j = pi, pj
    return pairs, uu


def long_vowels_agree(u, h, pairs, uu):
    """The long vowels Urdu writes must be the ones the Hindi word has."""
    matched = set(pairs.values())
    ur = []
    for k, (a, _) in enumerate(uu):
        if k in matched:
            continue
        if u[a] == 'ہ' and k == len(uu) - 1:
            ur.append('A')
        elif u[a] in UR_LONG:
            ur.append(UR_LONG[u[a]])
    if ur[:1] == ['A'] and u[0] == 'ا' and h[0] in 'अइउ':
        ur = ur[1:]          # alif carrying a short first vowel
    # Urdu may also write short u/i with و/ی (خوشی khushi): optional.
    hi = []
    for c in h:
        if c in HI_LONG:
            hi.append((HI_LONG[c], False))
        elif c in 'ुउ':
            hi.append(('O', True))
        elif c in 'िइ':
            hi.append(('I', True))

    def match(i, j):
        if j == len(hi):
            return i == len(ur)
        cls, opt = hi[j]
        if i < len(ur) and ur[i] == cls and match(i + 1, j + 1):
            return True
        return opt and match(i, j + 1)
    return match(0, 0)


# --- phonemes -----------------------------------------------------------------
def is_vowel(tok):
    return tok.lstrip("',")[:1] in set('aeiouAEIOUV@&')


def build(u, h, toks):
    """Urdu phonemes from eSpeak Hindi's phonemes for h, or None."""
    if 'ع' in u:
        return None          # ع changes the vowels around it
    if u[0] == 'ا' and h[0] == 'आ' or u[0] == 'آ' and h[0] != 'आ':
        return None          # word-initial alif is a short vowel, آ is aa
    if u[-1] == 'ہ' and h[-1] == 'ह':
        return None          # Urdu final ہ is a vowel (بارہ baara), Hindi बारह is not
    units = dev_units(h)
    pairs, uu = align(u, units) if units else (None, None)
    if pairs is None or not long_vowels_agree(u, h, pairs, uu):
        return None
    toks = [t for t in toks if t and t not in (';', '.', '|', '||')]
    # One consonant phoneme per Hindi consonant; the n/m/N Hindi says for an
    # anusvara (संबंध) is set aside, it is Urdu's nun.
    allc = [k for k, t in enumerate(toks) if not is_vowel(t)]
    cons, anus, ci = [], [], 0
    for c in h:
        if c in DCONS:
            if ci >= len(allc):
                return None
            cons.append(allc[ci]); ci += 1
        elif c in 'ंँ' and ci < len(allc) and toks[allc[ci]] in ('n', 'm', 'N', 'n.', 'n^'):
            anus.append(allc[ci]); ci += 1
    if ci != len(allc) or len(cons) != len(units):
        return None
    for j, k in enumerate(cons):
        start, end = uu[pairs[j]]
        letter = u[start]
        if letter in SUB:
            toks[k] = SUB[letter] + ('h' if letter == 'ڑ' and end - start > 1 else '')
        elif toks[k] in NUKTA_SOUNDS:
            return None      # Hindi wrote a sound the Urdu letter does not have
    if toks[-1] == '@-':
        toks = toks[:-1]     # Hindi's release after a final cluster (जश्न); Urdu has none
    nas = [k for k, t in enumerate(toks) if '~' in t]
    nuns = [k for k, (a, _) in enumerate(uu) if u[a] in 'نں' and k not in pairs.values()]
    if len(nas) + len(anus) != len(nuns):
        return None
    for k in anus:
        if toks[k] != 'N':
            toks[k] = 'n'    # Urdu nun is n (Hindi घंटा assimilates it); ng stays
    if not anus and nas:
        # Hindi anusvara said as a nasal vowel: where Urdu writes nun (not
        # noon ghunna ں), say n.
        if len([k for k in nuns if u[uu[k][0]] == 'ن']) == len(nas):
            for k in nas:
                toks[k] = toks[k].replace('~', '') + 'n'
        elif any(u[uu[k][0]] == 'ن' for k in nuns):
            return None
    return ''.join(t.replace('@4', '@') for t in toks)


def espeak_x(lang, words):
    tmp = os.path.join(os.path.dirname(os.path.abspath(__file__)), '_in.txt')
    out = []
    for i in range(0, len(words), 2000):
        with open(tmp, 'w', encoding='utf-8') as f:
            f.write('\n'.join(w + ' .' for w in words[i:i + 2000]))
        r = subprocess.run([S.EXE, '-q', '-x', '--sep=_', '-v', lang, '-f', tmp],
                           capture_output=True, env=dict(os.environ, ESPEAK_DATA_PATH=S.DATA)).stdout
        out += [l.strip() for l in r.decode('utf-8').splitlines() if l.strip()]
    os.remove(tmp)
    return out


def entries(dak, min_share):
    mapped = [(u, h) for u, (h, s) in urdu_to_hindi(dak).items() if s >= min_share and ' ' not in u]
    hi = espeak_x('hi', [h for _, h in mapped])
    out = {}
    for (u, h), p in zip(mapped, hi):
        b = build(u, h, p.split('_'))
        if b:
            out[u] = b
    return out


def main():
    dak, src, dst = sys.argv[1:4]
    min_share = float(sys.argv[4]) if len(sys.argv) > 4 else 0.2
    raw = open(src, encoding='utf-8', newline='').read()
    nl = '\r\n' if '\r\n' in raw else '\n'
    if HEADER in raw:
        raw = raw[:raw.index(HEADER)].rstrip('\r\n') + nl
    have = {l.split('\t')[0].split(' ')[0] for l in raw.split(nl) if l and not l.startswith('//')}
    new = {u: p for u, p in entries(dak, min_share).items() if u not in have}
    keep = sorted(new)
    lines = [HEADER,
             '// from Google\'s Dakshina dataset (CC BY-SA 4.0): Urdu words mapped to their',
             '// Hindi spelling, which writes the short vowels, and read by eSpeak\'s Hindi.',
             '// Regenerate with that tool rather than editing by hand. To correct a',
             '// word, add it above this block: the tool leaves out words listed there.',
             '']
    lines += ['%s\t%s' % (w, new[w]) for w in keep]
    open(dst, 'w', encoding='utf-8', newline='').write(raw + nl + nl.join(lines) + nl)
    print('entries written', len(keep), 'of', len(new))


if __name__ == '__main__':
    main()
