#!/usr/bin/env python3
"""Regenerate android/assets/emoji/ from NVDA's CLDR dictionaries.

NVDA reads emoji by name from its per-language cldr.dic files, generated by
https://github.com/nvaccess/nvda-cldr (the "main-out" branch holds the
output). This keeps the same entries NVDA uses for emoji, in the same
languages:

  git clone --depth 1 --branch main-out https://github.com/nvaccess/nvda-cldr.git
  python android/tools/update_emoji_names.py nvda-cldr/locale

Output: emoji/ids.txt holds one emoji sequence per line (English order);
emoji/<locale>.txt holds the name for each line of ids.txt, or an empty line
where that language has no name of its own (English is used then, as NVDA
does). Locale file names are lower-cased NVDA locale names (pt_br, zh_cn).
"""
import codecs
import os
import sys


def is_emoji(ident):
    # Identifiers with an astral character, a char in U+2300-U+27BF or
    # U+FE00-U+FE0F, a ZWJ, a keycap mark, or U+203C / U+2049. The rest of
    # cldr.dic (plain punctuation, maths, letters) is left to the symbol
    # processor.
    for ch in ident:
        c = ord(ch)
        if (c > 0xFFFF or 0x2300 <= c <= 0x27BF or 0xFE00 <= c <= 0xFE0F
                or c in (0x200D, 0x20E3, 0x203C, 0x2049)):
            return True
    return False


def load(path):
    names = {}
    for line in codecs.open(path, encoding="utf-8-sig"):
        parts = line.rstrip("\r\n").split("\t")
        if len(parts) < 2 or parts[0] == "symbols:" or parts[0].startswith("#"):
            continue
        if is_emoji(parts[0]):
            # Last wins, like NVDA's dictionary loader.
            names.pop(parts[0], None)
            names[parts[0]] = parts[1]
    return names


def main():
    src = sys.argv[1]
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "emoji")
    os.makedirs(out, exist_ok=True)
    for old in os.listdir(out):
        os.remove(os.path.join(out, old))
    english = load(os.path.join(src, "en", "cldr.dic"))
    ids = list(english)
    with open(os.path.join(out, "ids.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(ids) + "\n")
    for locale in sorted(os.listdir(src)):
        names = load(os.path.join(src, locale, "cldr.dic"))
        unknown = set(names) - set(english)
        assert not unknown, f"{locale}: {len(unknown)} emoji missing from English"
        with open(os.path.join(out, locale.lower() + ".txt"), "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(names.get(i, "") for i in ids) + "\n")


if __name__ == "__main__":
    main()
