/*
 * Copyright (C) 2026 eSpeak NG contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.animeshahilya.espeakng;

import android.content.Context;
import android.content.res.AssetManager;
import android.util.Log;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Emoji announcement by name, using NVDA's per-language CLDR dictionaries
 * (assets/emoji, generated by tools/update_emoji_names.py from nvda-cldr).
 * Names follow the voice's language the way NVDA's symbol lookup does: the
 * full locale, then its base language, then English for anything missing.
 * NVDA matches dictionary identifiers longest first, so full sequences (ZWJ
 * families, flags, skin-toned emoji, keycaps) resolve to a single name. Glue
 * codepoints with no name of their own - zero-width joiners, variation
 * selectors, lone regional indicators and the keycap mark - are dropped,
 * matching what NVDA's pass-through amounts to audibly. Emoji newer than the
 * data pass through raw.
 */
public final class NvdaEmoji {
    private static final String TAG = "NvdaEmoji";
    private static final String DIR = "emoji/";
    private static final String[] MISSING = new String[0];

    private static final class Node {
        final Map<Character, Node> next = new HashMap<Character, Node>();
        int index = -1;
    }

    private static volatile AssetManager sAssets;
    private static volatile Node sRoot;
    private static String[] sEnglish;
    private static final Map<String, String[]> sNames = new ConcurrentHashMap<String, String[]>();

    private NvdaEmoji() {
    }

    /** Called once from {@link EspeakApp#onCreate()}. */
    public static void init(Context context) {
        sAssets = context.getApplicationContext().getAssets();
    }

    private static List<String> readLines(String file) throws IOException {
        final List<String> lines = new ArrayList<String>(4096);
        try (BufferedReader in = new BufferedReader(new InputStreamReader(
                sAssets.open(DIR + file), StandardCharsets.UTF_8))) {
            String line;
            while ((line = in.readLine()) != null) {
                lines.add(line);
            }
        }
        return lines;
    }

    private static Node root() {
        Node root = sRoot;
        if (root != null) {
            return root;
        }
        synchronized (NvdaEmoji.class) {
            if (sRoot == null) {
                root = new Node();
                try {
                    final List<String> ids = readLines("ids.txt");
                    for (int i = 0; i < ids.size(); i++) {
                        final String id = ids.get(i);
                        Node node = root;
                        for (int j = 0; j < id.length(); j++) {
                            final char c = id.charAt(j);
                            Node child = node.next.get(c);
                            if (child == null) {
                                child = new Node();
                                node.next.put(c, child);
                            }
                            node = child;
                        }
                        node.index = i;
                    }
                    sEnglish = readLines("en.txt").toArray(new String[0]);
                } catch (IOException | RuntimeException e) {
                    Log.e(TAG, "emoji names unavailable", e);
                    root = new Node();
                }
                sRoot = root;
            }
            return sRoot;
        }
    }

    private static String[] namesFile(String locale) {
        String[] names = sNames.get(locale);
        if (names == null) {
            try {
                names = readLines(locale + ".txt").toArray(new String[0]);
            } catch (IOException e) {
                names = MISSING;
            }
            sNames.put(locale, names);
        }
        return names;
    }

    /** NVDA's lookup order: "pt-br" tries pt_br, then pt; null means English. */
    private static String[] namesFor(String languageTag) {
        if (languageTag == null || languageTag.isEmpty()) {
            return null;
        }
        final String locale = languageTag.toLowerCase(Locale.ROOT).replace('-', '_');
        String[] names = namesFile(locale);
        final int sep = locale.indexOf('_');
        if (names == MISSING && sep > 0) {
            names = namesFile(locale.substring(0, sep));
        }
        return names == MISSING ? null : names;
    }

    private static boolean isGlue(int codePoint) {
        return codePoint == 0x200D
                || (codePoint >= 0xFE00 && codePoint <= 0xFE0F)
                || (codePoint >= 0x1F1E6 && codePoint <= 0x1F1FF)
                || codePoint == 0x20E3;
    }

    /** {@link #substitute(String, String)} with English names. */
    public static String substitute(String cluster) {
        return substitute(cluster, "en");
    }

    /**
     * Replaces the emoji in {@code cluster} with CLDR names in the voice's
     * language, longest match first. Unknown non-glue codepoints pass through
     * raw.
     */
    public static String substitute(String cluster, String languageTag) {
        if (cluster == null || cluster.isEmpty()) {
            return cluster;
        }
        final Node root = root();
        final String[] local = namesFor(languageTag);
        final int len = cluster.length();
        StringBuilder sb = new StringBuilder(len + 16);
        int i = 0;
        while (i < len) {
            Node node = root;
            int j = i;
            int best = -1;
            int bestEnd = i;
            while (j < len) {
                node = node.next.get(cluster.charAt(j));
                if (node == null) {
                    break;
                }
                j++;
                if (node.index >= 0) {
                    best = node.index;
                    bestEnd = j;
                }
            }
            if (best >= 0) {
                String name = local != null && best < local.length ? local[best] : "";
                if (name.isEmpty()) {
                    name = sEnglish[best];
                }
                if (sb.length() > 0 && sb.charAt(sb.length() - 1) != ' ') {
                    sb.append(' ');
                }
                sb.append(name);
                i = bestEnd;
                continue;
            }
            int cp = cluster.codePointAt(i);
            int step = Character.charCount(cp);
            if (isGlue(cp)) {
                i += step;
                continue;
            }
            if (sb.length() > 0 && sb.charAt(sb.length() - 1) != ' ') {
                sb.append(' ');
            }
            sb.append(cluster, i, i + step);
            i += step;
        }
        return sb.toString();
    }
}
